### ISSUE TITLE
Can I use the released version on docker ?

### ISSUE THREAD

**Issue by rafilkmp3** [researchgate/azkaban-ldap-usermanager#18]
Can I use this on my dockerfile with latest version ? or I need to build ? 

```
# Add LDAP Plugin
ENV LDAP_USERMANAGER_VERSION="1.2.0"
ENV LDAP_USERMANAGER_PLUGIN_DOWNLOAD_URL="https://github.com/researchgate/azkaban-ldap-usermanager/releases/download/${LDAP_USERMANAGER_VERSION}/azkaban-ldap-usermanager-${LDAP_USERMANAGER_VERSION}.jar"
ADD ${LDAP_USERMANAGER_PLUGIN_DOWNLOAD_URL} /azkaban/extlib/azkaban-ldap-usermanager.jar
```

**Comment by Hillkorn** [comment]
Not sure if I get the question right but of course you can download the jar from the repository releases page.

**Comment by rafilkmp3** [comment]
@Hillkorn  do you have a way to enable a debug for the plugin ? I try to login and i can just get 

```
2020/03/31 14:34:11.103 +0000 INFO [LoginAbstractAzkabanServlet] [Azkaban] 172.18.0.1  -  "POST / - HTTP/1.1" browser
web_1       | 2020/03/31 14:34:11.109 +0000 DEBUG [log] [Azkaban] RESPONSE /  200
web_1       | 2020/03/31 14:37:31.179 +0000 DEBUG [log] [Azkaban] EXCEPTION
web_1       | java.net.SocketTimeoutException: Read timed out
web_1       | 	at java.net.SocketInputStream.socketRead0(Native Method)
web_1       | 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
web_1       | 	at java.net.SocketInputStream.read(SocketInputStream.java:171)
web_1       | 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
web_1       | 	at org.mortbay.io.ByteArrayBuffer.readFrom(ByteArrayBuffer.java:382)
web_1       | 	at org.mortbay.io.bio.StreamEndPoint.fill(StreamEndPoint.java:114)
web_1       | 	at org.mortbay.jetty.bio.SocketConnector$Connection.fill(SocketConnector.java:198)
web_1       | 	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:290)
web_1       | 	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
web_1       | 	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
web_1       | 	at org.mortbay.jetty.bio.SocketConnector$Connection.run(SocketConnector.java:228)
web_1       | 	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```

**Comment by eyalbenivri** [comment]
@rafilkmp3 Not sure if this error comes for the plugin... But to your question, logging is handled by azkaban as well. standard log4j.
